# HTTP Server配置
[server]
    # 端口号
	Address        = ":80"
	# 静态文件目录
	ServerRoot     = "public"
	# 入口文件
	IndexFiles     = ["index.html","main.html"]
	LogPath        = "./logs/server"
	NameToUriType  = 2
	RouteOverWrite = true

# 全局日志配置
[logger]
    Path   = "./logs"
    Level  = "all"
    Stdout = true

# 模板引擎配置
[viewer]
    Path        = "./template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# 数据库连接
[database]
    link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/mofan-blog"
    debug = true
    # 数据库日志对象配置
    [database.logger]
        Path   = "./logs/sql"
        Level  = "all"
        Stdout = true

# swagger api页面查看账号密码
[swagger]
    user        = "123"
    pass        = "123"
    schemes     = ["http"]
    version     = "1.0"
    title       = "示例服务API"
    description = """
`GoFrame`基础开发框架示例服务API接口文档。
    """
