name: MoFan-Blog-Main

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o output/linux/MoFan

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: MoFan-linux-latest
          path: output/linux/MoFan
